# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'gwapp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for gwapp
  pod 'Google/SignIn'

  target 'gwapp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'gwappTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'gwapp-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for gwapp-tvOS

  target 'gwapp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
